# This is a basic workflow to help you get started with Actions

name: Java ausführen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['11', '16']
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: java -cp java src/ch/teko/Vertiefungsarbeit/Main.java
      
      - run: cp src/ch/teko/Vertiefungsarbeit/Main.java src/ch/teko/Vertiefungsarbeit/Latest.java
