name: Copy
on: push
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: "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"
        src_path: tree/main/src/ch/teko/Vertiefungsarbeit/Main.java
        dst_path: tree/main/backup/
        dst_owner: b-tomasz
        dst_repo_name: ./
